//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TabletManagerWPF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("v+eF36CzUdM3TJk24JPRdU22/oMOH2dKAEICLVHrI/wBYRHcCX+3KXzbLKaIKH9ZaEORpiF9L46v7aQQT" +
            "+fPbOLo9+f4TLiJun68vfriWfH4Ic+Ev73OD7fl2NvxNeyWjq1GVN1Q/RyrHQFQ1EmbS+RuueO7cM4b")]
        public string PaperlessConnectionStringEnc {
            get {
                return ((string)(this["PaperlessConnectionStringEnc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.26.85.1:1521/dbadm;Persist Security Info=True;User ID=PAPERLESS;P" +
            "assword=kOOpaJ4uwsfG0WN4UCnt14;")]
        public string PaperlessConnectionString {
            get {
                return ((string)(this["PaperlessConnectionString"]));
            }
        }
    }
}
